### ISSUE TITLE
training limits not stored when pressing TAB key

### ISSUE THREAD

**Issue by SubOptimal** [kikmann/my-sports-challenge-issues#1]
A changed value in the training setup is not stored when pressing the TAB key. It is stored only after pressing the ENTER key. Hence it is not possible to change multiple values easily.

Assuming I want to change the value for "KM per point" and "AM per point".

I would expect the following input sequence to work.
- select first field with the mouse
- enter first value
- TAB key to go to next field
- enter second value

Instead, I have to
- select first field with the mouse
- enter first value
- press ENETR key
- select second field with the mouse
- enter second value
- press ENTER key

![image](https://user-images.githubusercontent.com/653288/154415475-8c88787d-eb08-4bc4-a60f-7cdc397cf028.png)

**Comment by kikmann** [comment]
Agreed, I need to check whether the plugin which I'm using can support this behaviour.

**Comment by kikmann** [comment]
relaunch of new system, closing old issues
