### ISSUE TITLE
date selector for manual trainings not functional

### ISSUE THREAD

**Issue by SubOptimal** [kikmann/my-sports-challenge-issues#2]
When I enter a training manually, the only selectable date is the current date.

![image](https://user-images.githubusercontent.com/653288/154898116-14f9962c-e9fe-472c-89f7-0e4f5e1b685f.png)

Either it is allowed to select any date, then the date selector doesn't work as expected.
If it's not foreseen to select a different date, then there should be no date selector and the current date should be pre-filled.

**Comment by kikmann** [comment]
I assume you were using your "Testbed" Challenge for this test, which starts 2022-02-21 and ends 2022-02-27.
The datepicker should not allow any date, but only dates that are within the challenge, not in the future and also only 3 days "back" (this is current default setting for all challenges and will be made configurable soon).

So if you want to enter a manual training on 2022-02-21 then the only possible date could be 2022-02-21, right ?
If you check today then you'll see that the date picker offers 2022-02-21 and 2022-02-22.
The current date is always preselected.

If you don't agree: what would be the desired behaviour ?

**Comment by SubOptimal** [comment]
Your assumption was right.

But there might is still something which is not working as expected.

Even the period is from 2022-02-21 till 2022-02-27 ...
![image](https://user-images.githubusercontent.com/653288/155662138-0b56fe12-bf07-4479-9829-dd37da1055ed.png)

... it seems the date selector does not allow entering training data for the first day.
![image](https://user-images.githubusercontent.com/653288/155662378-61e52f94-c4fb-40b0-a521-8ab622bc01ce.png)

Would it be possible to show days not belonging to the training in a different colour than the days you cannot enter data yet?

e.g.
![image](https://user-images.githubusercontent.com/653288/155663536-20637bf7-095f-41f2-8803-2162a4902bc5.png)

**Comment by kikmann** [comment]
relaunch of new system, closing old issues
