### ISSUE TITLE
inactivity logout

### ISSUE THREAD

**Issue by SubOptimal** [kikmann/my-sports-challenge-issues#3]
If there is some inactivity log out, then it behaves not consistent.

- when entering a manual training and no data is inserted for period x (I don't know about the exact period, maybe more than 5 min), then saving the data failed, and I had to log in again (sadly, all entered data were gone as well)
- when on the dashboard and not doing any interactions, there seems to be no such inactivity logout; the inactivity period was much longer than x

**Comment by kikmann** [comment]
Thanks for reporting, I will try to reproduce and come back with details.
I know there are some issues around inactivity and timing out of the tokens, but never took the time to troubleshoot.
Normally all interactions with the backend should be able to re-authorize automatically in a session.

**Comment by kikmann** [comment]
relaunch of new system, closing old issues
